=== basgoncalves/msk_modelling_python/virtual_environment/Lib/site-packages/CEINMS-master/cfg/XSD/calibration.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--Authors: Elena Ceseracciu, Claudio Pizzolato, Monica Reggiani -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation xml:lang="en"/>
  </xs:annotation>
  <xs:complexType name="SimulatedAnnealingType">
    <xs:sequence>
      <xs:element name="noEpsilon" type="xs:int"/>
      <xs:element name="rt" type="xs:double"/>
      <xs:element name="T" type="xs:double"/>
      <xs:element name="NS" type="xs:int"/>
      <xs:element name="NT" type="xs:int"/>
      <xs:element name="epsilon" type="xs:double"/>
      <xs:element name="maxNoEval" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="AlgorithmType">
    <xs:choice>
      <xs:element name="simulatedAnnealing" type="SimulatedAnnealingType"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="OpenLoopType"/>
  <xs:complexType name="TypeType">
    <xs:choice>
      <xs:element name="openLoop" type="OpenLoopType"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="TendonElementType">
    <xs:sequence>
      <xs:element name="tolerance" minOccurs="0" maxOccurs="1" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TendonType">
    <xs:choice>
      <xs:element name="stiff" type="TendonElementType"/>
      <xs:element name="integrationElastic" type="TendonElementType"/>
      <xs:element name="equilibriumElastic" type="TendonElementType"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="ActivationElementType"/>
  <xs:complexType name="ActivationType">
    <xs:choice>
      <xs:element name="exponential" type="ActivationElementType"/>
      <xs:element name="piecewise" type="ActivationElementType"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="NMSModelType">
    <xs:sequence>
      <xs:element name="type" type="TypeType"/>
      <xs:element name="tendon" type="TendonType"/>
      <xs:element name="activation" type="ActivationType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="TrialSetType">
    <xs:list itemType="xs:string"/>
  </xs:simpleType>
  <xs:complexType name="ObjectiveFunctionElementType"/>
  <xs:complexType name="GlobalParameterType"/>

  <xs:simpleType name="SingleParameterType">
    <xs:list itemType="xs:token"/>
  </xs:simpleType>
  
  <xs:complexType name="ObjectiveFunctionType">
    <xs:choice>
      <xs:element name="minimizeTorqueError" type="ObjectiveFunctionElementType"/>
    </xs:choice>
  </xs:complexType>
  <xs:simpleType name="DoFsType">
    <xs:list itemType="xs:token"/>
  </xs:simpleType>
  <xs:simpleType name="TwoDoublesType">
    <xs:list itemType="xs:double"/>
  </xs:simpleType>
  
  <xs:complexType name="RangeType">
    <xs:sequence>
       <xs:element name="range" type="TwoDoublesType"/>
    </xs:sequence>
  </xs:complexType>


  <xs:simpleType name="ParameterName">
    <xs:restriction base="xs:token">
      <xs:enumeration value="c1"/>
      <xs:enumeration value="c2"/>
      <xs:enumeration value="shapeFactor"/>
      <xs:enumeration value="optimalFibreLength"/>
      <xs:enumeration value="pennationAngle"/>
      <xs:enumeration value="tendonSlackLength"/>
      <xs:enumeration value="maxContractionVelocity"/>
      <xs:enumeration value="maxIsometricForce"/>
      <xs:enumeration value="strengthCoefficient"/>
      <xs:enumeration value="emDelay"/>
      <xs:enumeration value="percentageChange"/>
      <xs:enumeration value="damping"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="MuscleListType">
    <xs:list itemType="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="MuscleGroupsType">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="muscles" type="MuscleListType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ParameterType">
    <xs:sequence>
      <xs:element name="name" type="ParameterName"/>
      <xs:choice>
        <xs:element name="muscleGroups" type="MuscleGroupsType"/>
        <xs:element name="global" type="GlobalParameterType"/>
        <xs:element name="single" type="SingleParameterType"/>
      </xs:choice>
      <xs:choice>
        <xs:element name="absolute" type="RangeType"/>
        <xs:element name="relativeToSubjectValue" type="RangeType"/>
      </xs:choice>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="parameterSetType">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="parameter" type="ParameterType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StepType">
    <xs:sequence>
      <xs:element name="dofs" type="DoFsType"/>
      <xs:element name="objectiveFunction" type="ObjectiveFunctionType"/>
      <xs:element name="parameterSet" type="parameterSetType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CalibrationStepsType">
    <xs:sequence>
      <xs:element minOccurs="1" maxOccurs="unbounded" name="step" type="StepType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CalibrationType">
    <xs:sequence>
      <xs:element name="algorithm" type="AlgorithmType"/>
      <xs:element name="NMSmodel" type="NMSModelType"/>
      <xs:element name="calibrationSteps" type="CalibrationStepsType"/>
      <xs:element name="trialSet" type="TrialSetType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="calibration" type="CalibrationType"/>
</xs:schema>

=== basgoncalves/msk_modelling_python/msk_modelling_python/src/ceinms2/real-time-preprocessing/Template/calibration/calibrationCfg_FAI_bothLegs.xml
<?xml version="1.0" encoding="utf-8"?>
<calibration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="calibration.xsd">
   <algorithm>
      <simulatedAnnealing>
         <noEpsilon>4</noEpsilon>
         <rt>0.3</rt>
         <T>200000</T>
         <NS>15</NS>
         <NT>5</NT>
         <epsilon>1.E-5</epsilon>
         <maxNoEval>200000</maxNoEval>
      </simulatedAnnealing>
   </algorithm>
   <NMSmodel>
      <type>
         <openLoop/>
      </type>
      <tendon>
         <equilibriumElastic/>
      </tendon>
      <activation>
         <exponential/>
      </activation>
   </NMSmodel>
   <calibrationSteps>
      <step>
         <dofs>hip_flexion_r hip_adduction_r hip_rotation_r knee_flexion_r ankle_angle_r hip_flexion_l hip_adduction_l hip_rotation_l knee_flexion_l ankle_angle_l</dofs>
         <objectiveFunction>
            <torqueErrorNormalised>
               <targets>all</targets><!--<targetsType></targetsType>-->
               <weight>1</weight>
               <exponent>1</exponent>
            </torqueErrorNormalised>
            <penalty>
               <targets>all</targets>
               <targetsType>normalisedFibreLength</targetsType>
               <weight>100</weight>
               <exponent>2</exponent>
               <range>0.6 1.4</range>
            </penalty>
         </objectiveFunction>
         <parameterSet>
            <parameter>
               <name>c1</name>
               <single/>
               <absolute>
                  <range>-0.95 -0.05</range>
               </absolute>
            </parameter>
            <parameter>
               <name>c2</name>
               <single/>
               <absolute>
                  <range>-0.95 -0.05</range>
               </absolute>
            </parameter>
            <parameter>
               <name>shapeFactor</name>
               <single/>
               <absolute>
                  <range>-2.999 -0.001</range>
               </absolute>
            </parameter>
            <parameter>
               <name>tendonSlackLength</name>
               <single/>
               <relativeToSubjectValue>
                  <range>0.85 1.15</range>
               </relativeToSubjectValue>
            </parameter>
            <parameter>
               <name>optimalFibreLength</name>
               <single/>
               <relativeToSubjectValue>
                  <range>0.85 1.15</range>
               </relativeToSubjectValue>
            </parameter>
            <parameter>
               <name>strengthCoefficient</name>
               <single/>
               <absolute>
                  <range>0.8 2</range>
               </absolute>
            </parameter>
         </parameterSet>
      </step>
   </calibrationSteps>
   <trialSet>E:\3-PhD\Data\MocapData\ElaboratedData\009\pre\ceinms\trials\Run_baseline1.xml E:\3-PhD\Data\MocapData\ElaboratedData\009\pre\ceinms\trials\Run_baseline2.xml</trialSet>
</calibration>
