=== basgoncalves/msk_modelling_python/virtual_environment/Lib/site-packages/CEINMS-master/cfg/XSD/subject.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--Authors: Elena Ceseracciu, Claudio Pizzolato, Monica Reggiani -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation xml:lang="en"/>
  </xs:annotation>

  <xs:complexType name="AngleInputType">
    <xs:simpleContent>
      <xs:extension base="xs:double">
        <xs:attribute name="unit" default="rad">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="deg" />
              <xs:enumeration value="rad" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  
  <xs:complexType name="MTUType">
    <xs:sequence>
      <xs:element name="name" type="xs:token"/>
      <xs:element minOccurs="0" name="emDelay" type="xs:double"/>
      <xs:element name="c1" type="xs:double"/>
      <xs:element name="c2" type="xs:double"/>
      <xs:element name="shapeFactor" type="xs:double"/>
      <xs:element name="optimalFibreLength" type="xs:double"/>
      <xs:element name="pennationAngle" type="AngleInputType"/>
      <xs:element name="tendonSlackLength" type="xs:double"/>
      <xs:element minOccurs="0" name="maxContractionVelocity" type="xs:double"/>
      <xs:element minOccurs="0" name="damping" type="xs:double"/>
      <xs:element name="maxIsometricForce" type="xs:double"/>
      <xs:element name="strengthCoefficient" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MTUSetType">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="1" name="mtu" type="MTUType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="MTUNameSetType">
    <xs:list itemType="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="DoFType">
    <xs:sequence>
      <xs:element name="name" type="xs:token"/>
      <xs:element name="mtuNameSet" type="MTUNameSetType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="CalibrationSequenceType">
    <xs:list itemType="xs:token"/>
  </xs:simpleType>
  <xs:complexType name="CalibratedType">
    <xs:sequence>
      <xs:element name="startSubjectFile" type="xs:string"/>
      <xs:element name="calibrationSequence" type="CalibrationSequenceType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="UncalibratedType">
    <xs:sequence>
      <xs:element name="subjectID" type="xs:token"/>
      <xs:element name="additionalInfo" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CalibrationInfoType">
    <xs:choice>
      <xs:element name="uncalibrated" type="UncalibratedType"/>
      <xs:element name="calibrated" type="CalibratedType"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="DoFSetType">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="1" name="dof" type="DoFType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="PointsSequenceType">
    <xs:list itemType="xs:double"/>
  </xs:simpleType>
  <xs:complexType name="CurveType">
    <xs:sequence>
      <xs:element name="name" type="xs:token"/>
      <xs:element name="xPoints" type="PointsSequenceType"/>
      <xs:element name="yPoints" type="PointsSequenceType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MTUDefaultType">
    <xs:sequence>
      <xs:element name="emDelay" type="xs:double"/>
      <xs:element name="percentageChange" type="xs:double"/>
      <xs:element name="damping" type="xs:double"/>
      <xs:element maxOccurs="4" minOccurs="0" name="curve" type="CurveType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SubjectType">
    <xs:sequence>
      <xs:element name="mtuDefault" type="MTUDefaultType"/>
      <xs:element name="mtuSet" type="MTUSetType"/>
      <xs:element name="dofSet" type="DoFSetType"/>
      <xs:element name="calibrationInfo" type="CalibrationInfoType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="subject" type="SubjectType"/>
</xs:schema>

=== basgoncalves/msk_modelling_python/tests/settings_ceinms/PC002/trial2_r1/ceinms/calibratedSubject.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<subject xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="subject.xsd">
  <mtuDefault>
    <emDelay>0.015</emDelay>
    <percentageChange>0.15</percentageChange>
    <damping>0.1</damping>
    <curve>
      <name>activeForceLength</name>
      <xPoints>-5 0 0.401 0.402 0.4035 0.52725 0.62875 0.71875 0.86125 1.045 1.2175 1.4387 1.6187 1.62 1.621 2.2 5</xPoints>
      <yPoints>0 0 0 0 0 0.22667 0.63667 0.85667 0.95 0.99333 0.77 0.24667 0 0 0 0 0</yPoints>
    </curve>
    <curve>
      <name>passiveForceLength</name>
      <xPoints>-5 0.998 0.999 1 1.1 1.2 1.3 1.4 1.5 1.6 1.601 1.602 5</xPoints>
      <yPoints>0 0 0 0 0.035 0.12 0.26 0.55 1.17 2 2 2 2</yPoints>
    </curve>
    <curve>
      <name>forceVelocity</name>
      <xPoints>-10 -1 -0.6 -0.3 -0.1 0 0.1 0.3 0.6 0.8 10</xPoints>
      <yPoints>0 0 0.08 0.2 0.55 1 1.4 1.6 1.7 1.75 1.75</yPoints>
    </curve>
    <curve>
      <name>tendonForceStrain</name>
      <xPoints>0 0.001 0.002 0.003 0.004 0.005 0.006 0.007 0.008 0.009 0.01 0.011 0.012 0.013 0.014 0.015 0.016 0.017 0.018 0.019 0.02 0.021 0.022 0.023 0.024 0.025 0.026 0.027 0.028 0.029 0.03 0.031 0.032 0.033 0.034 0.035 0.036 0.037 0.038 0.039 0.04 0.041 0.042 0.043 0.044 0.045 0.046 0.047 0.048 0.049 0.05 0.051 0.052 0.053 0.054 0.055 0.056 0.057 0.058 0.059 0.06 0.061 0.062 0.063 0.064 0.065 0.066 0.067 0.068 0.069 0.07 0.071 0.072 0.073 0.074 0.075 0.076 0.077 0.078 0.079 0.08 0.081 0.082 0.083 0.084 0.085 0.086 0.087 0.088 0.089 0.09 0.091 0.092 0.093 0.094 0.095 0.096 0.097 0.098 0.099 0.1</xPoints>
      <yPoints>0 0.0012652 0.0073169 0.016319 0.026613 0.037604 0.049078 0.060973 0.073315 0.086183 0.099678 0.11386 0.12864 0.14386 0.15928 0.17477 0.19041 0.20658 0.22365 0.24179 0.26094 0.28089 0.30148 0.32254 0.34399 0.36576 0.38783 0.41019 0.43287 0.45591 0.4794 0.50344 0.52818 0.55376 0.58022 0.60747 0.63525 0.66327 0.69133 0.71939 0.74745 0.77551 0.80357 0.83163 0.85969 0.88776 0.91582 0.94388 0.97194 1 1.0281 1.0561 1.0842 1.1122 1.1403 1.1684 1.1964 1.2245 1.2526 1.2806 1.3087 1.3367 1.3648 1.3929 1.4209 1.449 1.477 1.5051 1.5332 1.5612 1.5893 1.6173 1.6454 1.6735 1.7015 1.7296 1.7577 1.7857 1.8138 1.8418 1.8699 1.898 1.926 1.9541 1.9821 2.0102 2.0383 2.0663 2.0944 2.1224 2.1505 2.1786 2.2066 2.2347 2.2628 2.2908 2.3189 2.3469 2.375 2.4031 2.4311</yPoints>
    </curve>
  </mtuDefault>
  <mtuSet>
    <mtu>
      <name>glut_med1_r</name>
      <c1>-0.0913647877437667</c1>
      <c2>-0.810963774529252</c2>
      <shapeFactor>-1.94114069032868</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0298777101357623</optimalFibreLength>
      <pennationAngle unit="rad">0.13962634</pennationAngle>
      <tendonSlackLength>0.0587050062268722</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>819</maxIsometricForce>
      <strengthCoefficient>0.925028229621265</strengthCoefficient>
    </mtu>
    <mtu>
      <name>glut_med2_r</name>
      <c1>-0.5</c1>
      <c2>-0.5</c2>
      <shapeFactor>0.1</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.045907456780792</optimalFibreLength>
      <pennationAngle unit="rad">0</pennationAngle>
      <tendonSlackLength>0.0411343230664747</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>573</maxIsometricForce>
      <strengthCoefficient>1</strengthCoefficient>
    </mtu>
    <mtu>
      <name>glut_med3_r</name>
      <c1>-0.5</c1>
      <c2>-0.5</c2>
      <shapeFactor>0.1</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0352392584976178</optimalFibreLength>
      <pennationAngle unit="rad">0.33161256</pennationAngle>
      <tendonSlackLength>0.0413020942143685</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>653</maxIsometricForce>
      <strengthCoefficient>1</strengthCoefficient>
    </mtu>
    <mtu>
      <name>glut_min1_r</name>
      <c1>-0.206340220343639</c1>
      <c2>-0.0893871883297221</c2>
      <shapeFactor>-1.24239725943785</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0361959674952169</optimalFibreLength>
      <pennationAngle unit="rad">0.17453293</pennationAngle>
      <tendonSlackLength>0.0143839257894384</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>270</maxIsometricForce>
      <strengthCoefficient>0.888039796136357</strengthCoefficient>
    </mtu>
    <mtu>
      <name>glut_min2_r</name>
      <c1>-0.5</c1>
      <c2>-0.5</c2>
      <shapeFactor>0.1</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0310178561934964</optimalFibreLength>
      <pennationAngle unit="rad">0</pennationAngle>
      <tendonSlackLength>0.0205730678834415</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>285</maxIsometricForce>
      <strengthCoefficient>1</strengthCoefficient>
    </mtu>
    <mtu>
      <name>glut_min3_r</name>
      <c1>-0.5</c1>
      <c2>-0.5</c2>
      <shapeFactor>0.1</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0210550137698618</optimalFibreLength>
      <pennationAngle unit="rad">0.01745329</pennationAngle>
      <tendonSlackLength>0.0403686354234192</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>323</maxIsometricForce>
      <strengthCoefficient>1</strengthCoefficient>
    </mtu>
    <mtu>
      <name>semimem_r</name>
      <c1>-0.658331553086947</c1>
      <c2>-0.131713309121983</c2>
      <shapeFactor>-0.400556443983276</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0474237306871126</optimalFibreLength>
      <pennationAngle unit="rad">0.26179939</pennationAngle>
      <tendonSlackLength>0.278917555815692</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>1288</maxIsometricForce>
      <strengthCoefficient>1.86211737418744</strengthCoefficient>
    </mtu>
    <mtu>
      <name>semiten_r</name>
      <c1>-0.0520050660725732</c1>
      <c2>-0.545910519730216</c2>
      <shapeFactor>-1.68001541184729</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0990194798449414</optimalFibreLength>
      <pennationAngle unit="rad">0.08726646</pennationAngle>
      <tendonSlackLength>0.203064373086281</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>410</maxIsometricForce>
      <strengthCoefficient>1.53511764885403</strengthCoefficient>
    </mtu>
    <mtu>
      <name>bifemlh_r</name>
      <c1>-0.391850032044435</c1>
      <c2>-0.794181646168401</c2>
      <shapeFactor>-2.59624124881741</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0651267290962173</optimalFibreLength>
      <pennationAngle unit="rad">0</pennationAngle>
      <tendonSlackLength>0.238065592750343</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>896</maxIsometricForce>
      <strengthCoefficient>1.85094759971923</strengthCoefficient>
    </mtu>
    <mtu>
      <name>bifemsh_r</name>
      <c1>-0.343810846278268</c1>
      <c2>-0.569119846186712</c2>
      <shapeFactor>-2.97383901486251</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.101734058678553</optimalFibreLength>
      <pennationAngle unit="rad">0.40142573</pennationAngle>
      <tendonSlackLength>0.0655311039144888</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>804</maxIsometricForce>
      <strengthCoefficient>1.46308175908689</strengthCoefficient>
    </mtu>
    <mtu>
      <name>sar_r</name>
      <c1>-0.589857173375652</c1>
      <c2>-0.634490493484298</c2>
      <shapeFactor>-2.39870464186529</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.27390288785048</optimalFibreLength>
      <pennationAngle unit="rad">0</pennationAngle>
      <tendonSlackLength>0.0834198028390011</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>156</maxIsometricForce>
      <strengthCoefficient>0.87833491012299</strengthCoefficient>
    </mtu>
    <mtu>
      <name>add_long_r</name>
      <c1>-0.449557481612598</c1>
      <c2>-0.299232459486679</c2>
      <shapeFactor>-1.34084533219398</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0819948990755516</optimalFibreLength>
      <pennationAngle unit="rad">0.10471976</pennationAngle>
      <tendonSlackLength>0.102773291235912</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>627</maxIsometricForce>
      <strengthCoefficient>1.77396771141697</strengthCoefficient>
    </mtu>
    <mtu>
      <name>add_brev_r</name>
      <c1>-0.425798821985534</c1>
      <c2>-0.884052552873318</c2>
      <shapeFactor>-1.61477983947264</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0729535197000818</optimalFibreLength>
      <pennationAngle unit="rad">0</pennationAngle>
      <tendonSlackLength>0.0173781086868922</tendonSlackLength>
      <maxContractionVelocity>10</maxContractionVelocity>
      <maxIsometricForce>429</maxIsometricForce>
      <strengthCoefficient>1.27788323618274</strengthCoefficient>
    </mtu>
    <mtu>
      <name>add_mag1_r</name>
      <c1>-0.5</c1>
      <c2>-0.5</c2>
      <shapeFactor>0.1</shapeFactor>
      <activationScale>1</activationScale>
      <optimalFibreLength>0.0498473436481702</optimalFibreLength>
      <pennationAngle unit="rad">0.08726646</pennationAngle>
